import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, ReportStatus } from '@prisma/client';
import { PaginationUtil } from 'src/common/utils/pagination.util';
import { PrismaService } from 'src/prisma/prisma.service';
import {
  ModerationDecision,
  ModerationDecisionDto,
} from './dto/moderation-decision.dto';
import { ModerationQueryDto } from './dto/moderation-query.dto';

@Injectable()
export class ModerationService {
  constructor(private readonly prisma: PrismaService) {}

  private readonly reportInclude = {
    rule: { select: { id: true, title: true, severity: true } },
    post: {
      select: {
        id: true,
        content: true,
        isDeleted: true,
        autoFlagged: true,
        createdAt: true,
        user: {
          select: {
            id: true,
            username: true,
            displayName: true,
            avatarUrl: true,
          },
        },
      },
    },
    reporter: {
      select: { id: true, username: true, displayName: true, avatarUrl: true },
    },
    user: {
      select: { id: true, username: true, displayName: true, avatarUrl: true },
    },
  } as const;

  async findAll(query: ModerationQueryDto) {
    const page = query.page ?? 1;
    const limit = query.limit ?? 20;
    const where: Prisma.ReportWhereInput = {
      ...(query.status === 'all'
        ? {}
        : { status: query.status ?? ReportStatus.PENDING }),
      ...(query.autoGenerated === undefined
        ? {}
        : { isAutoGenerated: query.autoGenerated }),
    };
    const [data, total] = await Promise.all([
      this.prisma.report.findMany({
        where,
        skip: PaginationUtil.getSkip(page, limit),
        take: limit,
        orderBy: { createdAt: 'asc' },
        include: this.reportInclude,
      }),
      this.prisma.report.count({ where }),
    ]);
    return PaginationUtil.paginate(data, total, { page, limit });
  }

  async decide(id: string, dto: ModerationDecisionDto) {
    const report = await this.prisma.report.findUnique({
      where: { id },
      select: { id: true, postId: true, isAutoGenerated: true },
    });
    if (!report) throw new NotFoundException('Report not found');

    if (
      (dto.action === ModerationDecision.HIDE ||
        dto.action === ModerationDecision.RESTORE) &&
      !report.postId
    ) {
      throw new NotFoundException('This report has no post to moderate');
    }

    await this.prisma.$transaction(async (tx) => {
      if (dto.action === ModerationDecision.HIDE && report.postId) {
        await tx.post.update({
          where: { id: report.postId },
          data: { isDeleted: true, autoFlagged: true },
        });
      }

      if (dto.action === ModerationDecision.RESTORE && report.postId) {
        await tx.post.update({
          where: { id: report.postId },
          data: { isDeleted: false, autoFlagged: false },
        });
      }

      if (
        dto.action === ModerationDecision.DISMISS &&
        report.isAutoGenerated &&
        report.postId
      ) {
        await tx.post.update({
          where: { id: report.postId },
          data: { isDeleted: false, autoFlagged: false },
        });
      }

      await tx.report.update({
        where: { id },
        data: {
          status:
            dto.action === ModerationDecision.DISMISS
              ? ReportStatus.DISMISSED
              : ReportStatus.RESOLVED,
        },
      });
    });

    return this.findOne(id);
  }

  private async findOne(id: string) {
    const report = await this.prisma.report.findUnique({
      where: { id },
      include: this.reportInclude,
    });
    if (!report) throw new NotFoundException('Report not found');
    return report;
  }
}
