import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import { KeywordsService } from 'src/modules/admin/keywords/keywords.service';
import { SettingsService } from 'src/modules/admin/settings/settings.service';
import { NotificationsService } from 'src/modules/notifications/notifications.service';
import { PrismaService } from 'src/prisma/prisma.service';

@Injectable()
export class PostModerationService {
  private readonly logger = new Logger(PostModerationService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly keywordsService: KeywordsService,
    private readonly settingsService: SettingsService,
    private readonly notificationService: NotificationsService,
  ) {}

  async assertContentLength(content: string): Promise<void> {
    const maxPostLength = await this.settingsService.getNumber(
      'content.max_post_length',
    );
    if (content.length > maxPostLength) {
      throw new BadRequestException(
        `Post content cannot exceed ${maxPostLength} characters`,
      );
    }
  }

  async handleKeywordScan(
    postId: string,
    authorId: string,
    content: string,
  ): Promise<{ matched: boolean; autoHidden: boolean }> {
    try {
      const keywordScanEnabled = await this.settingsService.getBoolean(
        'moderation.keyword_scan_enabled',
      );
      if (!keywordScanEnabled) return { matched: false, autoHidden: false };

      const scanResult = this.keywordsService.scanContent(content);
      if (!scanResult.matched) return { matched: false, autoHidden: false };

      const ruleIds = [...new Set(scanResult.matches.map((m) => m.ruleId))];
      const existingReports = await this.prisma.report.findMany({
        where: {
          postId,
          ruleId: { in: ruleIds },
          isAutoGenerated: true,
        },
        select: { ruleId: true },
      });
      const reportedRuleIds = new Set(
        existingReports.map((report) => report.ruleId),
      );
      const newRuleIds = ruleIds.filter(
        (ruleId) => !reportedRuleIds.has(ruleId),
      );

      if (newRuleIds.length > 0) {
        await Promise.all(
          newRuleIds.map((ruleId) =>
            this.prisma.report.create({
              data: {
                reporterId: null,
                isAutoGenerated: true,
                postId,
                userId: authorId,
                ruleId,
                status: 'PENDING',
                details: `Auto-detected by keyword filter (action: ${scanResult.action})`,
              },
            }),
          ),
        );
      }

      const autoHidden = scanResult.action === 'AUTO_HIDE';
      if (autoHidden) {
        await this.prisma.post.update({
          where: { id: postId },
          data: { isDeleted: true, autoFlagged: true },
        });
      } else {
        await this.prisma.post.update({
          where: { id: postId },
          data: { autoFlagged: true },
        });
      }

      const moderationMessage = autoHidden
        ? 'Your post was hidden because it may violate our content rules. It has been sent to moderators for review.'
        : scanResult.action === 'WARN'
          ? 'Your post may violate our content rules. Please review and edit it; moderators have been notified.'
          : 'Your post was flagged for moderator review. It remains visible while the review is pending.';
      await this.notificationService.sendSystemNotification({
        userId: authorId,
        postId,
        message: moderationMessage,
      });

      return { matched: true, autoHidden };
    } catch (error) {
      this.logger.error('Keyword scan failed', error);
      return { matched: false, autoHidden: false };
    }
  }
}
