import { BadRequestException } from '@nestjs/common';
import { PostModerationService } from './post-moderation.service';

const makeDeps = () => ({
  prisma: {
    report: { findMany: jest.fn(), create: jest.fn() },
    post: { update: jest.fn() },
  },
  keywordsService: { scanContent: jest.fn() },
  settingsService: { getBoolean: jest.fn(), getNumber: jest.fn() },
  notificationService: { sendSystemNotification: jest.fn() },
});

describe('PostModerationService', () => {
  it('rejects content longer than the configured maximum', async () => {
    const deps = makeDeps();
    deps.settingsService.getNumber.mockResolvedValue(5);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(service.assertContentLength('too long')).rejects.toThrow(
      BadRequestException,
    );
  });

  it('skips keyword scan when moderation setting is disabled', async () => {
    const deps = makeDeps();
    deps.settingsService.getBoolean.mockResolvedValue(false);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(
      service.handleKeywordScan('post-1', 'author-1', 'clean content'),
    ).resolves.toEqual({ matched: false, autoHidden: false });
    expect(deps.keywordsService.scanContent).not.toHaveBeenCalled();
  });

  it('creates reports and hides the post for AUTO_HIDE matches', async () => {
    const deps = makeDeps();
    deps.settingsService.getBoolean.mockResolvedValue(true);
    deps.keywordsService.scanContent.mockReturnValue({
      matched: true,
      action: 'AUTO_HIDE',
      matches: [{ ruleId: 'rule-1' }],
    });
    deps.prisma.report.findMany.mockResolvedValue([]);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(
      service.handleKeywordScan('post-1', 'author-1', 'bad content'),
    ).resolves.toEqual({ matched: true, autoHidden: true });
    expect(deps.prisma.report.create).toHaveBeenCalledWith({
      data: {
        reporterId: null,
        isAutoGenerated: true,
        postId: 'post-1',
        userId: 'author-1',
        ruleId: 'rule-1',
        status: 'PENDING',
        details: 'Auto-detected by keyword filter (action: AUTO_HIDE)',
      },
    });
    expect(deps.prisma.post.update).toHaveBeenCalledWith({
      where: { id: 'post-1' },
      data: { isDeleted: true, autoFlagged: true },
    });
  });
});
