import { BadRequestException } from '@nestjs/common';
import { PostModerationService } from './post-moderation.service';

const makeDeps = () => ({
  prisma: {
    report: { findMany: jest.fn(), findFirst: jest.fn(), create: jest.fn() },
    post: { update: jest.fn() },
    rule: { upsert: jest.fn() },
  },
  keywordsService: { scanContent: jest.fn() },
  settingsService: { getBoolean: jest.fn(), getNumber: jest.fn() },
  notificationService: { sendSystemNotification: jest.fn() },
});

describe('PostModerationService', () => {
  it('rejects content longer than the configured maximum', async () => {
    const deps = makeDeps();
    deps.settingsService.getNumber.mockResolvedValue(5);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(service.assertContentLength('too long')).rejects.toThrow(
      BadRequestException,
    );
  });

  it('skips keyword scan when moderation setting is disabled', async () => {
    const deps = makeDeps();
    deps.settingsService.getBoolean.mockResolvedValue(false);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(
      service.handleKeywordScan('post-1', 'author-1', 'clean content'),
    ).resolves.toEqual({ matched: false, autoHidden: false });
    expect(deps.keywordsService.scanContent).not.toHaveBeenCalled();
  });

  it('creates reports and hides the post for AUTO_HIDE matches', async () => {
    const deps = makeDeps();
    deps.settingsService.getBoolean.mockResolvedValue(true);
    deps.keywordsService.scanContent.mockReturnValue({
      matched: true,
      action: 'AUTO_HIDE',
      matches: [{ ruleId: 'rule-1' }],
    });
    deps.prisma.report.findMany.mockResolvedValue([]);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(
      service.handleKeywordScan('post-1', 'author-1', 'bad content'),
    ).resolves.toEqual({ matched: true, autoHidden: true });
    expect(deps.prisma.report.create).toHaveBeenCalledWith({
      data: {
        reporterId: null,
        isAutoGenerated: true,
        postId: 'post-1',
        userId: 'author-1',
        ruleId: 'rule-1',
        status: 'PENDING',
        details: 'Auto-detected by keyword filter (action: AUTO_HIDE)',
      },
    });
    expect(deps.prisma.post.update).toHaveBeenCalledWith({
      where: { id: 'post-1' },
      data: { isDeleted: true, autoFlagged: true },
    });
  });

  it('creates one auto report when image moderation flags uploaded media', async () => {
    const deps = makeDeps();
    deps.prisma.rule.upsert.mockResolvedValue({ id: 'image-rule' });
    deps.prisma.report.findFirst.mockResolvedValue(null);
    const service = new PostModerationService(
      deps.prisma as any,
      deps.keywordsService as any,
      deps.settingsService as any,
      deps.notificationService as any,
    );

    await expect(
      service.handleImageScanResult('post-1', 'author-1', [
        {
          key: 'posts/image.png',
          url: 'https://cdn.example.com/posts/image.png',
          mimetype: 'image/png',
          size: 1234,
          moderation: {
            status: 'FLAGGED',
            provider: 'aws-rekognition',
            labels: [
              {
                name: 'Violence',
                parentName: null,
                confidence: 75,
              },
            ],
            checkedAt: new Date('2026-08-05T00:00:00.000Z'),
            blockReason: null,
            shouldBlock: false,
            shouldReview: true,
          },
        },
      ] as any),
    ).resolves.toEqual({ matched: true, autoHidden: false });

    expect(deps.prisma.report.create).toHaveBeenCalledWith({
      data: {
        reporterId: null,
        isAutoGenerated: true,
        postId: 'post-1',
        userId: 'author-1',
        ruleId: 'image-rule',
        status: 'PENDING',
        details: 'Image 1: Violence (75.0%)',
      },
    });
    expect(deps.prisma.post.update).toHaveBeenCalledWith({
      where: { id: 'post-1' },
      data: { autoFlagged: true },
    });
    expect(deps.notificationService.sendSystemNotification).toHaveBeenCalled();
  });
});
