client_max_body_size 50m;

# --- 1. BLOCK REDIRECT (HTTP -> HTTPS) ---
server {
    listen 80;
    server_name staging.th-red.app staging-api.th-red.app;
    return 301 https://$host$request_uri;
}

# --- 2. FRONTEND (HTTPS) ---
server {
    listen 443 ssl;
    server_name staging.th-red.app;

    ssl_certificate /etc/letsencrypt/live/staging.th-red.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging.th-red.app/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://social-fe:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# --- 3. BACKEND (HTTPS) ---
server {
    listen 443 ssl;
    server_name staging-api.th-red.app;

    ssl_certificate /etc/letsencrypt/live/staging.th-red.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging.th-red.app/privkey.pem;

    location / {
        proxy_pass http://app:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
