import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, ReportStatus } from '@prisma/client';
import { PaginationUtil } from 'src/common/utils/pagination.util';
import { PrismaService } from 'src/prisma/prisma.service';
import { AdminReportQueryDto } from './dto/admin-report-query.dto';
import { UpdateReportDto } from './dto/update-report.dto';

@Injectable()
export class ReportsService {
  constructor(private readonly prisma: PrismaService) {}

  private readonly reportInclude = {
    rule: { select: { id: true, title: true, severity: true } },
    post: {
      select: {
        id: true,
        content: true,
        isDeleted: true,
        autoFlagged: true,
        createdAt: true,
      },
    },
    reporter: {
      select: { id: true, username: true, displayName: true, avatarUrl: true },
    },
    user: {
      select: {
        id: true,
        username: true,
        displayName: true,
        avatarUrl: true,
        status: true,
      },
    },
  } as const;

  async findAll(query: AdminReportQueryDto) {
    const page = query.page ?? 1;
    const limit = query.limit ?? 20;
    const where: Prisma.ReportWhereInput = {
      ...(query.status ? { status: query.status } : {}),
      ...(query.autoGenerated === undefined
        ? {}
        : { isAutoGenerated: query.autoGenerated }),
    };
    const [data, total] = await Promise.all([
      this.prisma.report.findMany({
        where,
        skip: PaginationUtil.getSkip(page, limit),
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: this.reportInclude,
      }),
      this.prisma.report.count({ where }),
    ]);

    return PaginationUtil.paginate(data, total, { page, limit });
  }

  async findOne(id: string) {
    const report = await this.prisma.report.findUnique({
      where: { id },
      include: this.reportInclude,
    });
    if (!report) throw new NotFoundException('Report not found');
    return report;
  }

  async update(id: string, dto: UpdateReportDto) {
    try {
      return await this.prisma.report.update({
        where: { id },
        data: { status: dto.status },
        include: this.reportInclude,
      });
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2025'
      ) {
        throw new NotFoundException('Report not found');
      }
      throw error;
    }
  }
}
