export type ReportStatus = "PENDING" | "REVIEWED" | "RESOLVED" | "DISMISSED";
export type PostFilterStatus = "all" | "visible" | "hidden" | "flagged";
export type ModerationDecision = "HIDE" | "RESTORE" | "RESOLVE" | "DISMISS";

export interface CommunityUser {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  status?: string;
}

export interface CommunityRule {
  id: string;
  title: string;
  severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
}

export interface AdminPost {
  id: string;
  content: string;
  isDeleted: boolean;
  autoFlagged: boolean;
  createdAt: string;
  updatedAt: string;
  user: CommunityUser;
  _count: { reports: number; media: number };
}

export interface CommunityPost {
  id: string;
  content: string;
  isDeleted: boolean;
  autoFlagged: boolean;
  createdAt: string;
  user?: CommunityUser;
}

export interface AdminReport {
  id: string;
  details: string | null;
  status: ReportStatus;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  rule: CommunityRule;
  post: CommunityPost | null;
  reporter: CommunityUser | null;
  user: CommunityUser | null;
}

export interface PaginationFilters {
  page: number;
  limit: number;
}

export interface AdminPostFilters extends PaginationFilters {
  search?: string;
  status?: PostFilterStatus;
}

export interface AdminReportFilters extends PaginationFilters {
  status?: ReportStatus;
  autoGenerated?: boolean;
}
