export type DashboardRange = "24h" | "7d" | "30d";

export interface AdminDashboard {
  range: DashboardRange;
  generatedAt: string;
  overview: {
    totalUsers: number;
    newUsers: number;
    postsCreated: number;
    repliesCreated: number;
    pendingReports: number;
    criticalReports: number;
    autoFlaggedPosts: number;
  };
  moderationQueue: DashboardModerationItem[];
  recentAuditLogs: DashboardAuditLog[];
  activity: DashboardActivityPoint[];
  health: DashboardHealth;
}

export interface DashboardModerationItem {
  id: string;
  isAutoGenerated: boolean;
  createdAt: string;
  rule: { title: string; severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" };
  post: { id: string; content: string; isDeleted: boolean } | null;
  user: { username: string; displayName: string | null } | null;
}

export interface DashboardAuditLog {
  id: string;
  action: string;
  actorType: string;
  createdAt: string;
  user: {
    id: string;
    username: string;
    displayName: string | null;
    avatarUrl: string | null;
  } | null;
}

export interface DashboardActivityPoint {
  date: string;
  users: number;
  posts: number;
}

export interface DashboardHealth {
  api: "healthy";
  database: "healthy";
  redis: "healthy" | "unavailable";
  checkedAt: string;
}
