import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { CacheService } from 'src/modules/cache/cache.service';
import { PrismaService } from 'src/prisma/prisma.service';
import {
  DashboardQueryDto,
  DashboardRange,
} from './dto/dashboard-query.dto';

type ActivityRow = { day: Date; count: number | bigint };

@Injectable()
export class DashboardService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly cacheService: CacheService,
  ) {}

  async getOverview(query: DashboardQueryDto) {
    const range = query.range ?? '7d';
    const from = this.getRangeStart(range);
    const healthCheckedAt = new Date();

    const [
      totalUsers,
      newUsers,
      postsCreated,
      repliesCreated,
      pendingReports,
      criticalReports,
      autoFlaggedPosts,
      moderationQueue,
      recentAuditLogs,
      userActivity,
      postActivity,
      redisHealthy,
    ] = await Promise.all([
      this.prisma.user.count({ where: { deletedAt: null } }),
      this.prisma.user.count({ where: { createdAt: { gte: from } } }),
      this.prisma.post.count({
        where: { createdAt: { gte: from }, parentPostId: null },
      }),
      this.prisma.post.count({
        where: { createdAt: { gte: from }, parentPostId: { not: null } },
      }),
      this.prisma.report.count({ where: { status: 'PENDING' } }),
      this.prisma.report.count({
        where: { status: 'PENDING', rule: { severity: 'CRITICAL' } },
      }),
      this.prisma.post.count({
        where: { autoFlagged: true, createdAt: { gte: from } },
      }),
      this.prisma.report.findMany({
        where: { status: 'PENDING' },
        orderBy: [{ rule: { severity: 'desc' } }, { createdAt: 'asc' }],
        take: 5,
        select: {
          id: true,
          isAutoGenerated: true,
          createdAt: true,
          rule: { select: { title: true, severity: true } },
          post: { select: { id: true, content: true, isDeleted: true } },
          user: { select: { username: true, displayName: true } },
        },
      }),
      this.prisma.auditLog.findMany({
        orderBy: { createdAt: 'desc' },
        take: 8,
        select: {
          id: true,
          action: true,
          actorType: true,
          createdAt: true,
          user: {
            select: { id: true, username: true, displayName: true, avatarUrl: true },
          },
        },
      }),
      this.queryDailyCounts('users', from),
      this.queryDailyCounts('posts', from),
      this.isRedisHealthy(),
    ]);

    return {
      range,
      generatedAt: healthCheckedAt,
      overview: {
        totalUsers,
        newUsers,
        postsCreated,
        repliesCreated,
        pendingReports,
        criticalReports,
        autoFlaggedPosts,
      },
      moderationQueue,
      recentAuditLogs,
      activity: this.toActivitySeries(range, from, userActivity, postActivity),
      health: {
        api: 'healthy' as const,
        database: 'healthy' as const,
        redis: redisHealthy ? ('healthy' as const) : ('unavailable' as const),
        checkedAt: healthCheckedAt,
      },
    };
  }

  private async isRedisHealthy(): Promise<boolean> {
    try {
      return await this.cacheService.ping();
    } catch {
      return false;
    }
  }

  private async queryDailyCounts(
    table: 'users' | 'posts',
    from: Date,
  ): Promise<ActivityRow[]> {
    return this.prisma.$queryRaw<ActivityRow[]>(Prisma.sql`
      SELECT date_trunc('day', "created_at") AS day, COUNT(*)::int AS count
      FROM ${Prisma.raw(`"${table}"`)}
      WHERE "created_at" >= ${from}
      GROUP BY 1
      ORDER BY 1 ASC
    `);
  }

  private toActivitySeries(
    range: DashboardRange,
    from: Date,
    users: ActivityRow[],
    posts: ActivityRow[],
  ) {
    const usersByDay = new Map(
      users.map((item) => [this.dayKey(item.day), Number(item.count)]),
    );
    const postsByDay = new Map(
      posts.map((item) => [this.dayKey(item.day), Number(item.count)]),
    );
    const days = range === '24h' ? 1 : Number.parseInt(range, 10);
    const start = new Date(from);
    start.setHours(0, 0, 0, 0);

    return Array.from({ length: days }, (_, index) => {
      const day = new Date(start);
      day.setDate(day.getDate() + index);
      const key = this.dayKey(day);
      return {
        date: key,
        users: usersByDay.get(key) ?? 0,
        posts: postsByDay.get(key) ?? 0,
      };
    });
  }

  private getRangeStart(range: DashboardRange): Date {
    const now = new Date();
    if (range === '24h') return new Date(now.getTime() - 24 * 60 * 60 * 1000);

    const days = Number.parseInt(range, 10);
    return new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
  }

  private dayKey(value: Date): string {
    return new Date(value).toISOString().slice(0, 10);
  }
}
