import type {
  DashboardRange,
  KeywordAction,
} from "./responses";
import type {
  ModerationDecision,
  PostFilterStatus,
  ReportStatus,
  RuleSeverity,
} from "../moderation/responses";

export interface PaginationFilters {
  page?: number;
  limit?: number;
}

export interface AuditLogFilters extends PaginationFilters {
  action?: string;
  actorType?: string;
  from?: string;
  to?: string;
}

export interface AdminPostFilters extends PaginationFilters {
  search?: string;
  status?: PostFilterStatus;
}

export interface AdminReportFilters extends PaginationFilters {
  status?: ReportStatus;
  autoGenerated?: boolean;
}

export interface DashboardQueryRequest {
  range: DashboardRange;
}

export interface CreateRuleRequest {
  title: string;
  description: string;
  severity: RuleSeverity;
  isActive: boolean;
  displayOrder: number;
}

export type UpdateRuleRequest = Partial<CreateRuleRequest>;

export interface CreateKeywordRequest {
  word: string;
  ruleId: string;
  action: KeywordAction;
}

export type UpdateKeywordRequest = Partial<CreateKeywordRequest>;

export interface CreateRoleRequest {
  name: string;
  level: number;
  description?: string;
}

export type UpdateRoleRequest = Partial<CreateRoleRequest>;

export interface CreateAdminUserRequest {
  username: string;
  email: string;
  password?: string;
  dateOfBirth?: string;
  roleIds: string[];
}

export interface UpdateAdminUserRequest extends CreateAdminUserRequest {}

export interface UpdateSystemSettingsRequest {
  registrationEnabled?: boolean;
  requireEmailVerification?: boolean;
  maxPostLength?: number;
  keywordScanEnabled?: boolean;
}

export interface ModerationDecisionRequest {
  action: ModerationDecision;
}
