import type { IsoDateTimeString } from "../common/api-envelope";
import type {
  ModerationDecision,
  PostFilterStatus,
  ReportStatus,
  RuleSeverity,
} from "../moderation/responses";

export interface AdminActorResponse {
  id: string;
  username: string;
  displayName: string;
  email?: string;
  avatarUrl: string | null;
  status?: string;
}

export interface AuditLogResponse {
  id: string;
  userId: string | null;
  action: string;
  actorType: string;
  ipAddress: string | null;
  userAgent: string | null;
  metadata: Record<string, unknown> | null;
  createdAt: IsoDateTimeString;
  actor: AdminActorResponse | null;
}

export interface CommunityRuleResponse {
  id: string;
  title: string;
  severity: RuleSeverity;
}

export interface AdminPostResponse {
  id: string;
  content: string;
  isDeleted: boolean;
  autoFlagged: boolean;
  createdAt: IsoDateTimeString;
  updatedAt: IsoDateTimeString;
  user: AdminActorResponse;
  _count: { reports: number; media: number };
}

export interface CommunityPostResponse {
  id: string;
  content: string;
  isDeleted: boolean;
  autoFlagged: boolean;
  createdAt: IsoDateTimeString;
  user?: AdminActorResponse;
}

export interface AdminReportResponse {
  id: string;
  details: string | null;
  status: ReportStatus;
  isAutoGenerated: boolean;
  createdAt: IsoDateTimeString;
  updatedAt: IsoDateTimeString;
  rule: CommunityRuleResponse;
  post: CommunityPostResponse | null;
  reporter: AdminActorResponse | null;
  user: AdminActorResponse | null;
}

export type DashboardRange = "24h" | "7d" | "30d";

export interface AdminDashboardResponse {
  range: DashboardRange;
  generatedAt: IsoDateTimeString;
  overview: {
    totalUsers: number;
    newUsers: number;
    postsCreated: number;
    repliesCreated: number;
    pendingReports: number;
    criticalReports: number;
    autoFlaggedPosts: number;
  };
  moderationQueue: DashboardModerationItemResponse[];
  recentAuditLogs: DashboardAuditLogResponse[];
  activity: DashboardActivityPointResponse[];
  health: DashboardHealthResponse;
}

export interface DashboardModerationItemResponse {
  id: string;
  isAutoGenerated: boolean;
  createdAt: IsoDateTimeString;
  rule: { title: string; severity: RuleSeverity };
  post: { id: string; content: string; isDeleted: boolean } | null;
  user: { username: string; displayName: string | null } | null;
}

export interface DashboardAuditLogResponse {
  id: string;
  action: string;
  actorType: string;
  createdAt: IsoDateTimeString;
  user: AdminActorResponse | null;
}

export interface DashboardActivityPointResponse {
  date: string;
  users: number;
  posts: number;
}

export interface DashboardHealthResponse {
  api: "healthy";
  database: "healthy";
  redis: "healthy" | "unavailable";
  checkedAt: IsoDateTimeString;
}

export type KeywordAction = "FLAG" | "AUTO_HIDE" | "WARN";

export interface RuleResponse {
  id: string;
  title: string;
  description: string;
  severity: RuleSeverity;
  isActive: boolean;
  displayOrder: number;
  createdAt: IsoDateTimeString;
  updatedAt: IsoDateTimeString;
  _count?: {
    reports: number;
    keywords: number;
  };
}

export interface KeywordResponse {
  id: string;
  word: string;
  ruleId: string;
  action: KeywordAction | string;
  createdAt: IsoDateTimeString;
  updatedAt: IsoDateTimeString;
  rule: RuleResponse;
}

export interface PermissionResponse {
  id: string;
  name: string;
  displayName: string;
  resource: string;
  action: string;
}

export interface PermissionGroupResponse {
  id: string;
  name: string;
  description: string;
  permissions: PermissionResponse[];
}

export interface RolePermissionsResponse {
  id: string;
  roleId: string;
  permissionId: string;
  createdAt: IsoDateTimeString;
  permissions: PermissionResponse[];
}

export type SystemSettingKey =
  | "account.registration_enabled"
  | "account.require_email_verification"
  | "content.max_post_length"
  | "moderation.keyword_scan_enabled";

export interface SystemSettingResponse {
  key: SystemSettingKey;
  category: string;
  label: string;
  description: string;
  value: boolean | number;
  defaultValue: boolean | number;
  isDefault: boolean;
  updatedAt: IsoDateTimeString | null;
  updatedById: string | null;
}
