import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  BCRYPT_SALT_ROUNDS: Joi.number().default(12),
  API_PREFIX: Joi.string().default('api/v1'),
  CORS_ORIGIN: Joi.string().required(),
  CORS_CREDENTIALS: Joi.boolean().default(true),
  CLIENT_URL: Joi.string().uri().required(),
  SERVER_URL: Joi.string().uri().required(),
  REDIS_URL: Joi.string().uri().required(),
  REDIS_HOST: Joi.string().optional(),
  REDIS_PORT: Joi.number().port().optional(),
  REDIS_USERNAME: Joi.string().optional(),
  REDIS_PASSWORD: Joi.when('NODE_ENV', {
    is: 'production',
    then: Joi.string().min(32).required(),
    otherwise: Joi.string().min(32).optional(),
  }),
  REDIS_TLS: Joi.boolean().default(false),
  REDIS_BULL_PREFIX: Joi.string().default('{bull}'),
  SOCKET_REDIS_ADAPTER_ENABLED: Joi.boolean().default(true),
  AWS_ACCESS_KEY_ID: Joi.string().optional(),
  AWS_SECRET_ACCESS_KEY: Joi.string().optional(),
  AWS_REGION: Joi.string().optional(),
  AWS_BUCKET_NAME: Joi.string().optional(),
  AWS_ENDPOINT: Joi.string().uri().optional(),
  CLOUDFRONT_DOMAIN: Joi.string().optional(),
  MAIL_HOST: Joi.string().optional(),
  MAIL_PORT: Joi.number().port().optional(),
  MAIL_USER: Joi.string().optional(),
  MAIL_PASSWORD: Joi.string().allow('').optional(),
  MAIL_FROM: Joi.string().optional(),
  MAIL_SECURE: Joi.boolean().default(false),
  GOOGLE_CLIENT_ID: Joi.string().optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().optional(),
  GOOGLE_CALLBACK_URL: Joi.string().uri().optional(),
  TWO_FACTOR_SECRET_KEY: Joi.string().min(32).optional(),
  THROTTLE_TTL: Joi.number().positive().optional(),
  THROTTLE_LIMIT: Joi.number().positive().optional(),
  SWAGGER_TITLE: Joi.string().optional(),
  SWAGGER_DESCRIPTION: Joi.string().optional(),
  SWAGGER_VERSION: Joi.string().optional(),
});
