"use client";

import { useMemo } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Flag, RotateCcw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { formatFullDate } from "@/app/utils/format.util";
import { useAuthStore } from "@/app/store/use-auth.store";
import DataTable from "../../components/table-data";
import { useAdminReports, useCommunityMutations } from "../../hooks/use-community";
import { AdminReport, ReportStatus } from "../../interfaces/community.interface";
import { ColumnDef } from "../../interfaces/column.interface";

const statuses: ReportStatus[] = ["PENDING", "REVIEWED", "RESOLVED", "DISMISSED"];
const statusClass: Record<ReportStatus, string> = {
  PENDING: "border-amber-200 bg-amber-50 text-amber-700",
  REVIEWED: "border-blue-200 bg-blue-50 text-blue-700",
  RESOLVED: "border-green-200 bg-green-50 text-green-700",
  DISMISSED: "border-slate-200 bg-slate-50 text-slate-700",
};

export default function ReportsPage() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const page = Number(searchParams.get("page")) || 1;
  const limit = Number(searchParams.get("limit")) || 10;
  const status = (searchParams.get("status") || "all") as ReportStatus | "all";
  const autoGenerated = (searchParams.get("autoGenerated") || "all") as "all" | "true" | "false";

  const updateParams = (key: string, value: string) => {
    const params = new URLSearchParams(searchParams.toString());
    if (value && value !== "all") params.set(key, value);
    else params.delete(key);
    if (key !== "page") params.set("page", "1");
    router.push(`${pathname}?${params.toString()}`);
  };
  const { data: response, isLoading } = useAdminReports({
    page,
    limit,
    status: status === "all" ? undefined : status,
    autoGenerated: autoGenerated === "all" ? undefined : autoGenerated === "true",
  });
  const { reportStatusMutation } = useCommunityMutations();
  const canResolve = useAuthStore((state) => state.permissions.includes("report:resolve"));
  const reports = response?.data ?? [];
  const meta = response?.meta ?? { total: 0, totalPages: 1 };

  const columns: ColumnDef<any>[] = useMemo(
    () => [
      {
        header: "Reported content",
        cell: (report: AdminReport) => (
          <div className="max-w-sm">
            <p className="line-clamp-2 font-medium text-slate-900">{report.post?.content || "Reported user"}</p>
            {report.details && <p className="mt-1 line-clamp-1 text-xs text-slate-500">{report.details}</p>}
          </div>
        ),
      },
      {
        header: "Rule",
        cell: (report: AdminReport) => (
          <div><p className="font-medium text-slate-800">{report.rule.title}</p><p className="text-xs text-slate-500">{report.rule.severity}</p></div>
        ),
      },
      {
        header: "Source",
        cell: (report) => report.isAutoGenerated ? <Badge variant="outline" className="border-violet-200 bg-violet-50 text-violet-700">Automatic</Badge> : <span className="text-sm text-slate-600">@{report.reporter?.username || "Unknown"}</span>,
      },
      {
        header: "Status",
        className: "whitespace-nowrap",
        cell: (report) => <Badge variant="outline" className={statusClass[report.status as ReportStatus]}>{report.status}</Badge>,
      },
      {
        header: "Created",
        className: "whitespace-nowrap text-sm text-slate-600",
        cell: (report) => formatFullDate(report.createdAt),
      },
      ...(canResolve ? [{
        header: "Update",
        className: "text-right whitespace-nowrap",
        cell: (report: AdminReport) => (
          <Select value={report.status} disabled={reportStatusMutation.isPending} onValueChange={(nextStatus: ReportStatus) => reportStatusMutation.mutate({ reportId: report.id, status: nextStatus })}>
            <SelectTrigger className="w-32"><SelectValue /></SelectTrigger>
            <SelectContent>{statuses.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent>
          </Select>
        ),
      }] : []),
    ],
    [canResolve, reportStatusMutation],
  );

  const clearFilters = () => router.push(pathname);
  return (
    <div className="flex h-[85vh] w-full flex-col overflow-hidden bg-gray-50/50">
      <div className="mb-5 flex shrink-0 flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><h1 className="flex items-center gap-2 text-2xl font-bold text-gray-900"><Flag className="size-6 text-blue-600" /> Reports</h1><p className="mt-1 text-sm text-gray-500">Track every community and automated report.</p></div>
        <p className="text-sm text-slate-500">{meta.total.toLocaleString()} reports</p>
      </div>
      <div className="mb-5 flex shrink-0 flex-wrap gap-3">
        <Select value={status} onValueChange={(value: ReportStatus | "all") => updateParams("status", value)}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{statuses.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select>
        <Select value={autoGenerated} onValueChange={(value: "all" | "true" | "false") => updateParams("autoGenerated", value)}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All sources</SelectItem><SelectItem value="true">Automatic</SelectItem><SelectItem value="false">User submitted</SelectItem></SelectContent></Select>
        {(status !== "all" || autoGenerated !== "all") && <Button variant="ghost" onClick={clearFilters}><RotateCcw /> Clear filters</Button>}
      </div>
      <DataTable data={reports} columns={columns} isLoading={isLoading} tableName="reports" page={page} limit={limit} totalItems={meta.total} totalPages={Math.max(meta.totalPages, 1)} changePage={(nextPage) => updateParams("page", String(nextPage))} changeLimit={(nextLimit) => updateParams("limit", String(nextLimit))} />
    </div>
  );
}
