"use client";

import { useMemo } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Check, EyeOff, Gavel, RotateCcw, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { formatFullDate } from "@/app/utils/format.util";
import DataTable from "../../components/table-data";
import { useCommunityMutations, useModerationQueue } from "../../hooks/use-community";
import {
  AdminReport,
  ModerationDecision,
  ReportStatus,
} from "../../interfaces/community.interface";
import { ColumnDef } from "../../interfaces/column.interface";

const queueStatuses: (ReportStatus | "all")[] = ["PENDING", "REVIEWED", "RESOLVED", "DISMISSED", "all"];

export default function ModerationPage() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const page = Number(searchParams.get("page")) || 1;
  const limit = Number(searchParams.get("limit")) || 10;
  const status = (searchParams.get("status") || "PENDING") as ReportStatus | "all";
  const autoGenerated = (searchParams.get("autoGenerated") || "all") as "all" | "true" | "false";

  const updateParams = (key: string, value: string) => {
    const params = new URLSearchParams(searchParams.toString());
    if (value) params.set(key, value);
    else params.delete(key);
    if (key !== "page") params.set("page", "1");
    router.push(`${pathname}?${params.toString()}`);
  };
  const { data: response, isLoading } = useModerationQueue({
    page,
    limit,
    status: status === "all" ? undefined : status,
    autoGenerated: autoGenerated === "all" ? undefined : autoGenerated === "true",
  });
  const { moderationMutation } = useCommunityMutations();
  const reports = response?.data ?? [];
  const meta = response?.meta ?? { total: 0, totalPages: 1 };

  const decide = (reportId: string, action: ModerationDecision) =>
    moderationMutation.mutate({ reportId, action });

  const columns: ColumnDef<any>[] = useMemo(
    () => [
      {
        header: "Content under review",
        cell: (report) => (
          <div className="max-w-sm">
            <p className="line-clamp-2 font-medium text-slate-900">{report.post?.content || "Reported user"}</p>
            <p className="mt-1 text-xs text-slate-500">by @{report.post?.user?.username || report.user?.username || "unknown"}</p>
          </div>
        ),
      },
      {
        header: "Reason",
        cell: (report) => (
          <div><p className="font-medium text-slate-800">{report.rule.title}</p><Badge variant="outline" className="mt-1 border-slate-200 bg-slate-50 text-slate-700">{report.rule.severity}</Badge></div>
        ),
      },
      {
        header: "Signal",
        cell: (report) => report.isAutoGenerated ? <Badge variant="outline" className="border-violet-200 bg-violet-50 text-violet-700">Automatic</Badge> : <span className="text-sm text-slate-600">Reported by @{report.reporter?.username || "unknown"}</span>,
      },
      {
        header: "Queued",
        className: "whitespace-nowrap text-sm text-slate-600",
        cell: (report) => formatFullDate(report.createdAt),
      },
      {
        header: "Decision",
        className: "text-right whitespace-nowrap",
        cell: (report) => (
          <div className="flex justify-end gap-2">
            {report.post && (
              <Button size="sm" variant="outline" disabled={moderationMutation.isPending} onClick={() => decide(report.id, report.post?.isDeleted ? "RESTORE" : "HIDE")}>
                {report.post.isDeleted ? <RotateCcw /> : <EyeOff />}
                {report.post.isDeleted ? "Restore" : "Hide"}
              </Button>
            )}
            <Button size="sm" variant="outline" disabled={moderationMutation.isPending} onClick={() => decide(report.id, "RESOLVE")}><Check /> Resolve</Button>
            <Button size="sm" variant="ghost" disabled={moderationMutation.isPending} onClick={() => decide(report.id, "DISMISS")}><X /> Dismiss</Button>
          </div>
        ),
      },
    ],
    [moderationMutation],
  );

  return (
    <div className="flex h-[85vh] w-full flex-col overflow-hidden bg-gray-50/50">
      <div className="mb-5 flex shrink-0 flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><h1 className="flex items-center gap-2 text-2xl font-bold text-gray-900"><Gavel className="size-6 text-blue-600" /> Moderation</h1><p className="mt-1 text-sm text-gray-500">Make a clear, auditable decision on reported content.</p></div>
        <p className="text-sm text-slate-500">{meta.total.toLocaleString()} items in queue</p>
      </div>
      <div className="mb-5 flex shrink-0 flex-wrap gap-3">
        <Select value={status} onValueChange={(value: ReportStatus | "all") => updateParams("status", value)}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent>{queueStatuses.map((item) => <SelectItem key={item} value={item}>{item === "all" ? "All statuses" : item}</SelectItem>)}</SelectContent></Select>
        <Select value={autoGenerated} onValueChange={(value: "all" | "true" | "false") => updateParams("autoGenerated", value)}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All signals</SelectItem><SelectItem value="true">Automatic</SelectItem><SelectItem value="false">User submitted</SelectItem></SelectContent></Select>
      </div>
      <DataTable data={reports} columns={columns} isLoading={isLoading} tableName="moderation items" page={page} limit={limit} totalItems={meta.total} totalPages={Math.max(meta.totalPages, 1)} changePage={(nextPage) => updateParams("page", String(nextPage))} changeLimit={(nextLimit) => updateParams("limit", String(nextLimit))} />
    </div>
  );
}
